const SCORE_MAP = {
  EASY: 0,
  NORMAL: 25,
  MEDIUM: 50,
  HARD: 100,
  IMPOSSIBLE: 150,
}

export const DIFFICULTY_MAP = {
  EASY: 500,
  NORMAL: 400,
  MEDIUM: 300,
  HARD: 200,
  IMPOSSIBLE: 100,
}

export const SCORE_DIFFICULTY_MAP = {
  [SCORE_MAP.EASY]: DIFFICULTY_MAP.EASY,
  [SCORE_MAP.NORMAL]: DIFFICULTY_MAP.NORMAL,
  [SCORE_MAP.MEDIUM]: DIFFICULTY_MAP.MEDIUM,
  [SCORE_MAP.HARD]: DIFFICULTY_MAP.HARD,
  [SCORE_MAP.IMPOSSIBLE]: DIFFICULTY_MAP.IMPOSSIBLE,
}
